server:
  port: 5454
  

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/whatsapp
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: nishanneupane
    
    
    
  jpa:
    hibernate:
      ddl-auto: update
      
    show-sql: true